//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AccelerometerSubject.h
//  @ Date : 7/14/2015
//  @ Author : 
//
//


#if !defined(_ACCELEROMETERSUBJECT_H)
#define _ACCELEROMETERSUBJECT_H

#include "Subject.h"
struct Cartesian;

class AccelerometerSubject : public Subject {
	public:
		int getData(int * x, int * y, int * z);
		int getData(Cartesian * c);
	protected:
		struct AccelData {
			int accX;
			int accY;
			int accZ;
		} accelData;
};

#endif  //_ACCELEROMETERSUBJECT_H
