//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : DRV8833_ChannelController.h
//  @ Date : 7/14/2015
//  @ Author : 
//
//


#if !defined(_DRV8833_CHANNELCONTROLLER_H)
#define _DRV8833_CHANNELCONTROLLER_H

#include "MotorController.h"
#include <Arduino.h>

class DRV8833_ChannelController : public MotorController {
public:
	DRV8833_ChannelController(int pinIN_1, int pinIN_2, int pinSleep, int pinFault,
			LockAccelerometerObserver *observer, int dirSign = 1,
			unsigned int minPower = 80);
	virtual void init(LockSystemController * lsc); //decouple init operations from instantiation

protected:
	void applyMotorStopCommands();
	void applyMotorCoastCommands();
	void applyMotorDriveCommands();
	void applyMotorSleepCommands();
	void applyMotorWakeUpCommands();
	virtual int checkMotorFault();
private:
	int pinIN_1, pinIN_2, pinSleep, pinFault;
	void coastFastDecay();
	void reverse();
	void forward();
	void brakeSlowDecay();
	void forwardPWMfastDecay();
	void forwardPWMslowDecay();
	void reversePWMfastDecay();
	void reversePWMslowDecay();
};

#endif  //_DRV8833_CHANNELCONTROLLER_H
