//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LockAccelerometerObserver.cpp
//  @ Date : 7/14/2015
//  @ Author : 
//
//


#include "LockAccelerometerObserver.h"
#include <math.h>

LockAccelerometerObserver::LockAccelerometerObserver(AccelerometerSubject * subject, float alpha) :
	AccelerometerObserver(subject, alpha){
}

int LockAccelerometerObserver::getLockAngleDeg() {
	int angle=(180*atan2(filtCart.accX, filtCart.accY)/M_PI);
	return angle + 180;
}

/*
void LockAccelerometerObserver::getDoorPosition() {

}

void LockAccelerometerObserver::getLockOmega() {

}

void LockAccelerometerObserver::getLockAlpha() {

}
*/
