//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Observer.h
//  @ Date : 7/14/2015
//  @ Author :
//
//


#if !defined(_OBSERVER_H)
#define _OBSERVER_H

class Subject;

class Observer {
public:
	Observer(Subject * subject);
	virtual void Update() = 0;
protected:
	Subject * mySubject;
};

#endif  //_OBSERVER_H
