//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Observer.cpp
//  @ Date : 7/14/2015
//  @ Author : 
//
//


#include "Observer.h"
#include "Subject.h"

Observer::Observer(Subject * subject) :
	mySubject(subject)
{
	mySubject->Attach(this);
}

// probably not used
/*
Observer::~Observer(Subject & mySubject)
{
	mySubject->Detach(this);
}
*/
