//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Runnable.h
//  @ Date : 7/14/2015
//  @ Author : 
//
//


#if !defined(_RUNNABLE_H)
#define _RUNNABLE_H


class Runnable {
public:
	virtual void timeSlice() = 0;
};

#endif  //_RUNNABLE_H
