//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : STMACC_Subject.h
//  @ Date : 7/14/2015
//  @ Author :
//
//


#if !defined(_STMACC_SUBJECT_H)
#define _STMACC_SUBJECT_H

#include "AccelerometerSubject.h"
#include <Wire.h>

// consider changing these to consts and letting the compiler fold them away
#define ADDRESS_STMACC 0x19
#define CTRL_REG1_A 0x20
#define CTRL_REG4_A 0x23
#define CTRL_REG5_A 0x24
#define STATUS_REG_A 0x27
#define OUT_X_L_A 0x28



class STMACC_Subject : public AccelerometerSubject {
	public:
		// CTRL_REG1_A
		static const PROGMEM unsigned char Xen = 0x1;
		const PROGMEM unsigned char Yen = (0x1 << 1);
		const PROGMEM unsigned char Zen = (0x1 << 2);
		const PROGMEM unsigned char LPen = (0x1 << 3);
		const PROGMEM unsigned char ODR_PowerDown = 0x0;
		const PROGMEM unsigned char ODR_NormalLow1Hz = (0x1 << 4);
		const PROGMEM unsigned char ODR_NormalLow10Hz = (0x2 << 4);
		const PROGMEM unsigned char ODR_NormalLow25Hz = (0x3 << 4);
		const PROGMEM unsigned char ODR_NormalLow50Hz = (0x4 << 4);
		const PROGMEM unsigned char ODR_NormalLow100Hz = (0x5 << 4);
		const PROGMEM unsigned char ODR_NormalLow200Hz = (0x6 << 4);
		const PROGMEM unsigned char ODR_NormalLow400Hz = (0x7 << 4);
		const PROGMEM unsigned char ODR_Low1600Hz = (0x8 << 4);
		const PROGMEM unsigned char ODR_Normal1250Low5000Hz = (0x9 << 4);
		//CTRL_REG5_A
		const PROGMEM unsigned char BOOT = (0x1 << 7);
		const PROGMEM unsigned char FIFO_EN = (0x1 << 6);
		const PROGMEM unsigned char LIR_INT1 = (0x1 << 3);
		const PROGMEM unsigned char D4D_int1 = (0x1 << 2);
		enum ChipAddr {  LIS3DH = 0x18, LSM303DLHC = 0x19 };

		STMACC_Subject(ChipAddr ca);
		void init();
		void timeSlice();
		int getData(int * accX, int * accY, int * accZ);
	private:
		uint8_t buffer[ 6 ];
		uint8_t statusReg;
		int overWrite;
		int readSensorData();
		int sensorDataAvailable();
		unsigned int totFaults;
		unsigned int totOverwrites;;
		unsigned int conseqFaults;
		unsigned int consFaultThresh;
		int chipAddr;
		const PROGMEM char * const SPACE = " ";
};

#endif  //_STMACC_SUBJECT_H
