//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Subject.cpp
//  @ Date : 7/14/2015
//  @ Author : 
//
//


#include "Subject.h"
#include "Observer.h"


Subject::Subject()
{
}

int Subject::Attach(Observer * newObserver) {
	for (int idx = 0; idx < MAX_OBSERVERS; idx++) {
		if (myObservers[idx] == 0) {
			myObservers[idx] = newObserver;
			return 0;
		}
	}
	return -1;
}

int Subject::Detach(Observer * oldObserver) {
	for (int idx = 0; idx < MAX_OBSERVERS; idx++) {
		if (myObservers[idx] == oldObserver) {
			myObservers[idx] = 0;
			return 0;
		}
	}
	return -1;
}

void Subject::Notify() {
	for (int idx = 0; idx < MAX_OBSERVERS; idx++) {
		if (myObservers[idx] != 0) {
			(myObservers[idx])->Update();
		}
	}
}
